"""Pydantic models for multi-agent system validation and results."""

from typing import Literal, Optional

from pydantic import BaseModel, Field


class PreValidationResult(BaseModel):
    """Result from pre-validator agent.

    The pre-validator checks note structure, formatting, and frontmatter
    before expensive card generation.
    """

    is_valid: bool
    error_type: Literal["format", "structure", "frontmatter", "content", "none"]
    error_details: str = ""
    auto_fix_applied: bool = False
    fixed_content: Optional[str] = None
    validation_time: float = 0.0

    class Config:
        """Pydantic configuration."""

        frozen = False


class GeneratedCard(BaseModel):
    """Single card generated by generator agent.

    This represents an APF card with metadata for tracking.
    """

    card_index: int = Field(ge=1, description="1-based card index")
    slug: str = Field(min_length=1, description="Unique card identifier")
    lang: str = Field(pattern="^(en|ru)$", description="Card language")
    apf_html: str = Field(min_length=1, description="APF HTML content")
    confidence: float = Field(ge=0.0, le=1.0, description="Generation confidence score")

    class Config:
        """Pydantic configuration."""

        frozen = False


class GenerationResult(BaseModel):
    """Result from generator agent.

    Contains all cards generated from a single note.
    """

    cards: list[GeneratedCard]
    total_cards: int = Field(ge=0)
    generation_time: float = Field(ge=0.0)
    model_used: str

    class Config:
        """Pydantic configuration."""

        frozen = False


class PostValidationResult(BaseModel):
    """Result from post-validator agent.

    Validates generated cards for syntax, factual accuracy, and coherence.
    """

    is_valid: bool
    error_type: Literal["syntax", "factual", "semantic", "template", "none"]
    error_details: str = ""
    corrected_cards: Optional[list[GeneratedCard]] = None
    validation_time: float = 0.0

    class Config:
        """Pydantic configuration."""

        frozen = False


class AgentPipelineResult(BaseModel):
    """Complete result from the three-agent pipeline.

    Tracks results from pre-validation, generation, and post-validation stages.
    """

    success: bool
    pre_validation: PreValidationResult
    generation: Optional[GenerationResult] = None
    post_validation: Optional[PostValidationResult] = None
    total_time: float = Field(ge=0.0)
    retry_count: int = Field(ge=0, description="Number of post-validation retries")

    class Config:
        """Pydantic configuration."""

        frozen = False
